# Generated by Django 4.2.3 on 2024-08-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inverstor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(max_length=15)),
                ('joined_date', models.DateField()),
            ],
            options={
                'db_table': 'investor',
            },
        ),
    ]
