# Generated by Django 4.2.3 on 2024-08-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inverstor',
            new_name='Investor',
        ),
    ]
