# Generated by Django 4.2.3 on 2024-08-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_remove_investor_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
