# Generated by Django 4.2.3 on 2024-08-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_investor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='financial_goals',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='investor',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='investor',
            name='initial_investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='investor',
            name='investment_horizon',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='investor',
            name='risk_tolerance',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=50),
        ),
    ]
